---
version: '2.1'

services:
  private-beta-invitation-service:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
    volumes:
      - ./build/install/private-beta-invitation-service:/opt/app/
    ports:
      - 4700:4700
