emailTemplateMappings:
  - service: 'test-service'
    templateId: '95e66f73-3fe3-44b8-bf1c-bfbe39d287ff'
    notifyApiKey: ${NOTIFY_DEFAULT_API_KEY}
    welcomeLink: 'http://welcome-link-for-test-service.example.com'

notify:
  useStub: false

serviceBus:
  useStub: false
