server:
  port: 4700

management:
  security:
    enabled: false

notify:
  useStub: ${NOTIFY_USE_STUB:false}

serviceBus:
  useStub: ${SERVICE_BUS_USE_STUB:false}
  connectionString: ${SERVICE_BUS_CONNECTION_STRING:}
  pollingDelayInMs: ${SERVICE_BUS_POLLING_DELAY_MS:30000}
  maxReceiveWaitTimeInMs: ${SERVICE_BUS_MAX_RECEIVE_WAIT_TIME_MS:30000}

app-insights:
  request-component: off

emailTemplateMappings:
  - service: 'test-service'
    templateId: 'a57025a3-3780-4d13-8fb9-45af7fedb448'
    notifyApiKey: ${TEST_SERVICE_NOTIFY_API_KEY}
    welcomeLink: 'http://welcome-link-for-test-service.example.hmcts.net'
