server:
  port: 4700

management:
  security:
    enabled: false

notify:
  useStub: ${NOTIFY_USE_STUB:false}

serviceBus:
  useStub: ${SERVICE_BUS_USE_STUB:false}
  connectionString: ${SERVICE_BUS_CONNECTION_STRING:}
  pollingDelayInMs: ${SERVICE_BUS_POLLING_DELAY_MS:30000}

emailTemplateMappings:

---
spring:
  profiles: dev

notify:
  useStub: true

serviceBus:
  useStub: true
  pollingDelayInMs: ${SERVICE_BUS_POLLING_DELAY_MS:5000}

emailTemplateMappings:
  - service: 'test-service-1'
    templateId: 'test-service-1-template'
    notifyApiKey: 'test-service-1-key'
    welcomeLink: 'http://welcome-link-for-test-service-1.example.com'
  - service: 'test-service-2'
    templateId: 'test-service-2-template'
    notifyApiKey: 'test-service-2-key'
    welcomeLink: 'http://welcome-link-for-test-service-2.example.com'
